repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: ^tests/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^tests/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-xml
        files: |
          ^dap4/dap4\.xsd$
          ^tests/data/.*\.dmr$
      - id: trailing-whitespace
        files: |
          ^dap4/.*$
          ^tests/.*$
      - id: end-of-file-fixer
        files: |
          ^dap4/.*$
          ^tests/.*$
